spring.application.name=hr-login

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/altrium_recruitment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Niduli@10982
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8080

# File uploads (candidate CVs)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
app.upload.cv-dir=uploads/cvs

# Email (for password reset) — using Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rminiduli@gmail.com
spring.mail.password=mkyw prao rrzp nzcg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Base URL of your frontend
app.frontend.base-url=http://127.0.0.1:5500/altrium-full/frontend